Traceback (most recent call last):
  File "/home/neu/xcy/MHXGMDA/main.py", line 194, in <module>
    average_performance = selector.calculate_average_performance(fold_results)
  File "/home/neu/xcy/MHXGMDA/models.py", line 397, in calculate_average_performance
    'metrics_sum': np.zeros_like(metrics),
  File "<__array_function__ internals>", line 200, in zeros_like
  File "/home/neu/anaconda3/envs/HGTMDA/lib/python3.8/site-packages/numpy/core/numeric.py", line 139, in zeros_like
    res = empty_like(a, dtype=dtype, order=order, subok=subok, shape=shape)
  File "<__array_function__ internals>", line 200, in empty_like
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (13,) + inhomogeneous part.
 auc:0.9617 ,aupr:0.9548,f1_score:0.9381, accuracy:0.9333, recall:0.9681, specificity:0.8953, precision:0.9100, ndcg:0.9919

Process finished with exit code 1
